# ログインボーナス受取履歴を格納するdbを指定します
mysql_loginbonus_info:
  host: "localhost"
  port: "3306"
  user: "root"
  pass: "rootpass"
  db: "loginbonus_info"

# ログイン履歴を格納しているdbを指定します
mysql_connection_data:
    host: "localhost"
    port: "3306"
    user: "root"
    pass: "rootpass"
    db: "connection_data"

# プラグインの状態を指定します。onにすると有効、offにすると無効になります
status: "on"

# ログインの対象となるサーバー名を指定します
target_server_name: "man10"

# プレイヤーが対象のサーバーにログインしたときに表示されるメッセージにディレイを設定します (1000 = 1秒)
onPlayerJoinEventDelay: 2000

# プレイヤーがログインした時、そのログイン日において開催期間中のログボが存在しない、且つその月のいずれかの日が任意のログボの開催期間に含まれていないとき、
# ・開催期間がその月の始めから終わり
# ・その他の内容（報酬設定など）が「月更新用ログボ」という名前のログボの内容と同様
# である新規ログボを自動的に作成します。onにするとこの機能が有効、offにすると無効になります
auto_create_loginbonuses: "off"

# 各報酬枠報酬の受け取り時に実行されるコマンドを指定します
# <player>は受け取ったプレイヤー名に置き換えられます
# 例：
# commands_when_claimed_normal_rewards:
#   - "tell <player> normalテストメッセージ"
# と書くことで、報酬を受け取ったプレイヤーに対して「normalテストメッセージ」という文字列をチャットに送信します
commands_when_claimed_normal_rewards:

commands_when_claimed_special_rewards:

commands_when_claimed_bonus_rewards:

commands_when_claimed_continuous_rewards:
