mysql_loginbonus_info:
  host: "localhost"
  port: "3306"
  user: "root"
  pass: "rootpass"
  db: "loginbonus_info"

mysql_connection_data:
    host: "localhost"
    port: "3306"
    user: "root"
    pass: "rootpass"
    db: "connection_data"

target_server_name: "man10"
commands_when_claimed_normal_rewards:
  - "tell <player> normalテストメッセージ"
commands_when_claimed_special_rewards:
  - "tell <player> specialテストメッセージ"
commands_when_claimed_bonus_rewards:
  - "tell <player> bonusテストメッセージ"
commands_when_claimed_continuous_rewards:
  - "tell <player> continuousテストメッセージ"