mysql_loginbonus_info:
  host: "localhost"
  port: "3306"
  user: "root"
  pass: "rootpass"
  db: "loginbonus_info"

mysql_connection_data:
    host: "localhost"
    port: "3306"
    user: "root"
    pass: "rootpass"
    db: "connection_data"

target_server_name: "man10"